### ISSUE TITLE
sys-apps/file-5.37-r1::tgbugs-overlay - "A file is not listed in the Manifest"

### ISSUE THREAD

**Issue by redblade7** [tgbugs/tgbugs-overlay#5]
Attempting to install sys-apps/file-5.37-r1::tgbugs-overlay fails with the error:

`>>> Verifying ebuild manifests`
`!!! A file is not listed in the Manifest: '/var/db/repos/tgbugs-overlay/sys-apps/file/files/file-5.38-Revert-PR-93-iaeiaeiaeiae-Do-as-the-comment-says-and.patch'`

**Comment by tgbugs** [comment]
`files/` is probably a broken symlink. Where is your portage repo located? the `files/` folder for many packages is currently symlinked against the old convention that the portage repo was located in `/usr/portage` and I have not had an opportunity to switch all my systems over. The quick fix is to manually resymlink `files` to the equivalent location.

**Comment by redblade7** [comment]
Which `files/` folder are you referring to? I'm not entirely familiar with the details of portage, but I use portage on tmpfs if that helps: https://wiki.gentoo.org/wiki/Portage_TMPDIR_on_tmpfs

**Comment by tgbugs** [comment]
`/var/db/repos/tgbugs-overlay/sys-apps/file/files` is a symlink that points to `/usr/portage/sys-apps/file/files` which probably does not exist on your system, but `/var/db/repos/gentoo/sys-apps/file/files` probably will.

**Comment by redblade7** [comment]
I have two Gentoo systems. The symlink points to `/usr/portage/sys-apps/file/files`
I don't have `/var/db/repos/gentoo/sys-apps/file/files`.

**Comment by tgbugs** [comment]
Thanks, this helped me figure out that I just needed to regenerate the manifest against the new state of the main portage tree. Should be fixed shortly.
